version: '3'

services:
  test_db:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: senha123
      POSTGRES_USER: tester
      POSTGRES_DB: blogtest
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
